<a href="https://colab.research.google.com/github/mohammad-salim-23/9amjobtaskclient/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
arr = [1,2,3]
print(arr*5) #5 time arr print korce kictu pottekta element ke 5 diye multiplication korte pare ni
arr = [x*5 for x in arr]
print(arr)

[1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3]
[5, 10, 15]


In [ ]:
import numpy as np
arr1 = np.array([1,2,3])
arr1 = arr1*5
print(arr1)


[ 5 10 15]


# **Ndarray**

In [ ]:
import numpy as np
# 1d array
arr1 = np.array([1,2,3,4,5])

#2d array
arr2 = np.array([[1,2,3],
                [4,5,6]])
#3d array
arr3 = np.array([
    #1st floor
    [[1,2,3],
     [4,5,6]],

    #2nd floor
    [[1,2,3],
     [4,5,6]],

    #3rd floor
    [[1,2,3],
     [4,5,6]]
])


# **Array attributes**

In [ ]:
#dimension
print(arr1.ndim)
print(arr2.ndim)
print(arr3.ndim)

#shape
print(arr1.shape)
print(arr2.shape)
print(arr3.shape)

#data type
print(arr1.dtype)
print(arr2.dtype)
print(arr3.dtype)

#size
print(arr1.size)
print(arr2.size)
print(arr3.size)

1
2
3
(5,)
(2, 3)
(3, 2, 3)
int64
int64
int64
5
6
18


###**ndarray data type**

In [ ]:
arr = np.array([1,2,3])

print(arr.dtype)

arr = np.array([1,2,3,3.5])
print(arr.dtype)

int64
float64


In [ ]:
arr = np.array([1,2,3.2])
#upcasting
print(arr.dtype)

#upcasted to string
arr = np.array([1,2,3.2,'H'])
print(arr.dtype)


float64
<U32


###**selecting a data type for an array**


In [ ]:
#arr = np.array([1,2,300],dtype = np.int8) #overflow
arr = np.array([1,2,300],dtype = np.int16)
print(arr.dtype)
print(arr)

arr = arr.astype(np.int32)
print(arr.dtype)

#error
#arr = np.array([1,2,3.2,'hellop'],dtype=np.float64)
print(arr.dtype)


int16
[  1   2 300]
int32
int32


###**ndarray creation from existing data**

In [ ]:
#list
lst = [10,20,30,40,40.5]

arr = np.array(lst,dtype = np.int32)
print(arr)
print(type(arr))
print(arr.dtype)

mixed_lst = [10,True,'Hello']
arr = np.array(mixed_lst)
print(arr)
print(type(arr))
print(arr.dtype)

matrix = [[1,2,3],
          [4,5,6]]

arr = np.array(matrix)
print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)
print(arr.size)

[10 20 30 40 40]
<class 'numpy.ndarray'>
int32
['10' 'True' 'Hello']
<class 'numpy.ndarray'>
<U21
[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>
int64
(2, 3)
2
6


In [ ]:
#tuple

tpl = (10,20,30)
arr = np.array(tpl,dtype = np.int32)
print(arr.dtype)
arr = arr.astype(np.int16)
print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)

int32
[10 20 30]
<class 'numpy.ndarray'>
int16
(3,)
1


In [ ]:
#set
st = {1,2,3}
arr = np.array(st);
print(type(arr))
print(arr.dtype) #object
print(arr) #set ei roice
arr = np.array(list(st))
print(type(arr))
print(arr.dtype)
print(arr)
arr = arr.astype(np.int16)
print(arr.dtype)
print(arr.shape)
print(arr.ndim)


<class 'numpy.ndarray'>
object
{1, 2, 3}
<class 'numpy.ndarray'>
int64
[1 2 3]
int16
(3,)
1


In [ ]:
#dictionary
dc = {'a':10,'b':20,'c':30}
keys = dc.keys()
values = dc.values()

items = dc.items()

In [ ]:
#keys to ndarray
arr = np.array(list(keys))
print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)
print(arr.size)

['a' 'b' 'c']
<class 'numpy.ndarray'>
<U1
(3,)
1
3


In [ ]:
#items to ndarray
arr = np.array(list(items))
print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)
print(arr.size)

[['a' '10']
 ['b' '20']
 ['c' '30']]
<class 'numpy.ndarray'>
<U21
(3, 2)
2
6


###**Creating ndarray from scratch**

In [ ]:
#np.zeroes
arr = np.zeros((2,3),dtype = np.int8)
print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)
print(arr.size)

arr = np.zeros_like(arr3)
print(arr)
print(arr.shape)

[[0 0 0]
 [0 0 0]]
<class 'numpy.ndarray'>
int8
(2, 3)
2
6
[[[0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]]]
(3, 2, 3)


In [ ]:
#np.ones
arr = np.ones((3,4,3),dtype=np.int8)
print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)
print(arr.size)

arr = np.ones_like(arr3) ##arr3 shape same
print(arr)
print(arr.shape)

[[[1 1 1]
  [1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]
  [1 1 1]]]
<class 'numpy.ndarray'>
int8
(3, 4, 3)
3
36
[[[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]]
(3, 2, 3)


In [ ]:
#np.empty
arr = np.empty_like(arr3) ##arr3 shape same
print(arr)
print(type(arr))
print(arr.dtype)
print(arr.ndim)
print(arr.shape)
print(arr.size)

arr = np.empty_like(arr3)
print(arr)
print(arr.shape)

[[[      736144144               0 134609944219632]
  [134609974045328        10858752 134609944219632]]

 [[134609537880048              97 134609981426912]
  [134609981426912 134609537877792        11711008]]

 [[       11664528        11711008 134609537877648]
  [134609929714400        11664576 134609929714400]]]
<class 'numpy.ndarray'>
int64
3
(3, 2, 3)
18
[[[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]]
(3, 2, 3)


In [ ]:
#np.full
arr = np.full((4,3),np.inf)
print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)
print(arr.size)

arr = np.full_like(arr3,np.inf,dtype = np.float64)

print(arr)
print(arr.shape)
print(arr.dtype)

[[inf inf inf]
 [inf inf inf]
 [inf inf inf]
 [inf inf inf]]
<class 'numpy.ndarray'>
float64
(4, 3)
2
12
[[[inf inf inf]
  [inf inf inf]]

 [[inf inf inf]
  [inf inf inf]]

 [[inf inf inf]
  [inf inf inf]]]
(3, 2, 3)
float64


###**array creation with random values**

In [ ]:
#np.random.rand(shape)
arr = np.random.rand(2,3) #0->1
print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)
print(arr.size)

[[0.32510779 0.40160961 0.04158014]
 [0.28560311 0.07404961 0.1280905 ]]
<class 'numpy.ndarray'>
float64
(2, 3)
2
6


In [ ]:
#np.random.randint(start,end,shape)
arr = np.random.randint(1,10,(2,3))
print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)
print(arr.size)

[[1 8 7]
 [3 4 4]]
<class 'numpy.ndarray'>
int64
(2, 3)
2
6


In [ ]:
#np.random.uniform(start,end,shape)
arr = np.random.uniform(50,100,(3,3,4))
print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)
print(arr.size)


[[[90.33525379 93.62434171 68.8646984  51.94575596]
  [84.65172603 70.60547145 65.72449745 65.39058887]
  [99.05412294 60.32679768 81.45950662 74.57357087]]

 [[62.87980288 79.5849852  97.04022059 74.67735907]
  [52.1793599  75.88912802 59.17325205 67.56532905]
  [50.73162969 76.7919378  52.66164547 93.39505487]]

 [[82.35223331 98.815864   56.85081932 95.89341851]
  [72.29980614 78.67033023 94.18036278 75.7623331 ]
  [60.01656302 88.36501729 61.40220495 54.17279405]]]
<class 'numpy.ndarray'>
float64
(3, 3, 4)
3
36


###**array creation with range function**

In [ ]:
# np.arange(first,end(not included),step) -> similar to range function
arr = np.arange(1,10,1)
mat = arr.reshape(3,3)
print(arr)
print(mat)
print(type(arr))

print(arr.dtype)
print(arr.shape)
print(arr.ndim)
print(arr.size)

[1 2 3 4 5 6 7 8 9]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
<class 'numpy.ndarray'>
int64
(9,)
1
9


In [ ]:
# np.linspace(0,4,6)
arr = np.linspace(0,8,10)
print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)
print(arr.size)

[0.         0.88888889 1.77777778 2.66666667 3.55555556 4.44444444
 5.33333333 6.22222222 7.11111111 8.        ]
<class 'numpy.ndarray'>
float64
(10,)
1
10


In [ ]:
#np.logspace(start,end(included),koita)
arr = np.logspace(0,10,6) #10^0 then 1
print(arr)
arr = np.logspace(0,10,6,base=2) #2^0 ..
print(arr)

[1.e+00 1.e+02 1.e+04 1.e+06 1.e+08 1.e+10]
[1.000e+00 4.000e+00 1.600e+01 6.400e+01 2.560e+02 1.024e+03]


##**creating matrix and linear lagebra**

In [ ]:
diagonal_matrix = np.diag([1,2,3,4])
print(diagonal_matrix)
print(diagonal_matrix.shape)

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]
(4, 4)


In [ ]:
#identity matrix
identity_mat = np.eye(4)
print(identity_mat)
print(identity_mat.shape)

#np.eye(row,column,k)

mat = np.eye(3,4)
print(mat)

mat = np.eye(3,4,-1)
print(mat)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
(4, 4)
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]]
[[0. 0. 0. 0.]
 [1. 0. 0. 0.]
 [0. 1. 0. 0.]]


###**indexing and slicing**

In [ ]:
#indexing
print(arr1)
print(arr2)

arr1[2] = 100
print(arr1)
print(arr2)
arr2[1][1]=500
print(arr2)

[  1   2 100   4   5]
[[  1   2   3]
 [  4   5 500]]
[  1   2 100   4   5]
[[  1   2   3]
 [  4   5 500]]
[[  1   2   3]
 [  4 500 500]]


In [ ]:
#slicing
#id = arr[start:end:step]
arr1_mod = arr1[1:4]
print(arr1_mod)
arr1_mod[0] = 100
print(arr1)
arr1_mod_an = arr1[1:4].copy()
print(arr1_mod_an)
arr1_mod_an[2]=300
print(arr1_mod_an)
print(arr1)

[100 100   4]
[  1 100 100   4   5]
[100 100   4]
[100 100 300]
[  1 100 100   4   5]


In [ ]:
#2d slicing
#arr[row_start:row_end : step, column_start:column_end:step]
print(arr2)
#getting a row
row_0 = arr2[0:1,]
print(row_0)
row_1 = arr2[1:,]
print(row_1)
#getting a column
col_0 = arr2[::,0:1]
print("\n column:")
print(col_0)
col_1 = arr2[::,1:2]
print(col_1)

#getting a portion
print("\n portion:")

portion = arr2[::,0:2]
print(portion)


[[  1   2   3]
 [  4 500 500]]
[[1 2 3]]
[[  4 500 500]]

 column:
[[1]
 [4]]
[[  2]
 [500]]

 portion:
[[  1   2]
 [  4 500]]


#**Advance Indexing**

In [ ]:
lst = np.array([10,20,30,40])
values = lst[[0,2,1]]
print(values)

[10 30 20]


In [ ]:
print(arr2)
print(arr2[[0,1],[1,2]])
#boolean kunu kicu diye
print(arr2[arr2<200])
arr2[arr2>4] = 1000
print(arr2)


[[   1    2    3]
 [   4 1000 1000]]
[   2 1000]
[1 2 3 4]
[[   1    2    3]
 [   4 1000 1000]]


In [ ]:
arr = np.array([[10,20,30],[100,200,300]])

#iteration
print(arr)
for i in np.nditer(arr):
  print(i)

[[ 10  20  30]
 [100 200 300]]
10
20
30
100
200
300


***numpy practice***

In [ ]:
import numpy as np
val = [20,30,40]
arr = np.array(val)
farArr = np.array(list(map(lambda x:x*1.8+32,arr)))
print(farArr)

TypeError: 'list' object is not callable

In [ ]:
import numpy as np
val = [20,30,40]
arr = np.array(val)
farArr = np.array((map(lambda x:x*1.8+32,arr)))
faArr = list(farArr)
print(faArr)

TypeError: iteration over a 0-d array

In [ ]:
val = [10,20,30]
arr = np.array(val)

farArr = arr*1.8+32
print(farArr)

[50. 68. 86.]


In [ ]:
listSec = [120,130,180,241]
arrSec = np.array(listSec,dtype = np.float64)
print(arrSec.shape)
print(arrSec.size)
print(type(arrSec))
print(arrSec.dtype)
arrMin = arrSec/60
print(arrMin)

(4,)
4
<class 'numpy.ndarray'>
float64
[2.         2.16666667 3.         4.01666667]


In [ ]:
import numpy as np
arr = np.random.randint(1,100,size=(10,5)) #sample-10,feature->5

In [ ]:
arr.shape

(10, 5)

In [ ]:
b =arr.reshape(5,10)
b.shape
b.ndim
b

array([[55, 96, 36, 55,  7, 29, 31, 38, 64, 57],
       [20, 75,  2, 88,  5, 73, 71, 98, 92, 98],
       [52, 98, 23, 13, 81, 91, 79,  9, 80, 91],
       [52, 76, 71, 60, 92, 44, 55, 26, 10,  3],
       [16, 28, 59, 53, 53, 79, 75, 56, 95, 81]])

In [ ]:
flatten = b.flatten()
print(flatten.ndim)
flatten
column_wise_flattening = np.ravel(b,order='F')
print(column_wise_flattening)

1
[55 20 52 52 16 96 75 98 76 28 36  2 23 71 59 55 88 13 60 53  7  5 81 92
 53 29 73 91 44 79 31 71 79 55 75 38 98  9 26 56 64 92 80 10 95 57 98 91
  3 81]


In [ ]:
a = np.random.randint(1,10,size=(2,3))
b = np.random.randint(1,10,size=(2,3))

In [ ]:
print(a)
print(b)

[[7 5 4]
 [6 4 2]]
[[6 2 6]
 [4 8 7]]


##**concatenate**

In [ ]:
con_row = np.concatenate((a,b),axis = 0) #row wise
print(con_row)
con_col = np.concatenate((a,b),axis=1) #column wise
print(con_col)


[[7 5 4]
 [6 4 2]
 [6 2 6]
 [4 8 7]]
[[7 5 4 6 2 6]
 [6 4 2 4 8 7]]


In [ ]:
#error
#row wise concatenate korar smy column same thakbe
#col wise concatenate korar smy row ta same thakte hobe
x = np.random.randint(1,10,size=(2,3))
y = np.random.randint(1,10,size=(3,3))
rx = np.concatenate((x,y),axis=0)
print(rx) #hobe karon column same
#ry = np.concatenate((x,y),axis=1) #hobe na karon x,y er row same na
#print(ry)


[[5 5 6]
 [8 7 3]
 [8 6 4]
 [9 2 8]
 [8 1 3]]


In [ ]:
#transpose
mat = np.array([[10,20,30],
                [30,40,50]])
transpose = mat.T
print(transpose)

[[10 30]
 [20 40]
 [30 50]]


In [ ]:
#array split
a = np.random.randint(1,10 , size=(10,))
a
splitted_array = np.array_split(a,3)
print(splitted_array)

#split->equal division
#splitted_array = np.split(a,3) #error asbe kenona se equally division kore kintu 10 ke equally 3 baage divide kora possible na
#print(splitted_array)

[array([1, 8, 4]), array([5, 7, 9]), array([1, 8, 7])]
[array([1, 8, 4]), array([5, 7, 9]), array([1, 8, 7])]


##**arithmetic operator and mathmatical functions**

In [ ]:
# faster for vectorization
x = np.array([10,8,30,100])
y = np.array([ 2 , 3 ,4  ,5 ])

add = np.add(x,y)
print(add)
sub = x-y
print(sub)
mul = x*y
print(mul)
div = x/y
print(div)

remainder = x%y
print(remainder)

[ 12  11  34 105]
[ 8  5 26 95]
[ 20  24 120 500]
[ 5.          2.66666667  7.5        20.        ]
[0 2 2 0]


In [ ]:
#mathmatical function
#trigonometry
#sin,cos , tan takes values in radian

sin_val = np.sin(x)
print(sin_val)

cos_val = np.cos(x)
print(cos_val)

deg_con = np.rad2deg(x)
print(deg_con)


[-0.54402111  0.98935825 -0.98803162 -0.50636564]
[-0.83907153 -0.14550003  0.15425145  0.86231887]
[ 572.95779513  458.3662361  1718.87338539 5729.57795131]


In [ ]:
#log
x = np.array([10,8,16,100])
base_10_log_val = np.log10(x)
print(base_10_log_val)

two_diye_bhag = np.log2(x)
print(two_diye_bhag)

sqrt = np.sqrt(x)
print(sqrt)



[1.         0.90308999 1.20411998 2.        ]
[3.32192809 3.         4.         6.64385619]
[ 3.16227766  2.82842712  4.         10.        ]


In [ ]:
#different
x = np.array([ 10 , 8 , 16 , 100 ])
s = np.sum(x)
print(s)

#prefix sum
cumul = np.cumsum(x)
print(cumul)

134
[ 10  18  34 134]


In [ ]:
#broadcasting
result = x +2
print(result)
#rulings = columns er size and vector er size same hote hobe
matrix = np.array([[10,20,30],
                [30,40,50]
               ])
result = matrix+2
result

vector = np.array([1,2,3,4])
#result = matrix+vector #error asbe karon column size same na
print(result)

[ 12  10  18 102]
[[12 22 32]
 [32 42 52]]


##**Logical functions**

In [ ]:
import numpy as np
# comparison - >,< , >= ,<= , == , !=
x = np.array([ 10 , 8 , 16 , 100 ])
y = np.array([ 2 , 3 ,16  ,5 ])

greater_than = x>y
print(greater_than)

equal = x==y

print(equal)

# all () -> shob true kina
# any() -> jekono ekta true ase kina

print(np.all(greater_than))

print(np.any(equal))

[ True  True False  True]
[False False  True False]
False
True


##**Sorting**

In [ ]:
#inplace


z = x.copy()
print(z)

z.sort()

print(z)

[ 10   8  16 100]
[  8  10  16 100]


In [ ]:
#copy sorting
print(x)
sort_arr = np.sort(x)

print(sort_arr)
print(x)

[ 10   8  16 100]
[  8  10  16 100]
[ 10   8  16 100]


In [ ]:
#2d array sorting
mat = np.array([[10,3,5],[8,4,9]])

#horizontal axis = 1
hor_sort = np.sort(mat,axis = 1)
print(hor_sort)

ver_sort = np.sort(mat,axis=0)
print(ver_sort)

[[ 3  5 10]
 [ 4  8  9]]
[[ 8  3  5]
 [10  4  9]]


##**Searching**

In [ ]:
print(x)

[ 10   8  16 100]


In [ ]:
# np.where(condition,x,y) if true x, otherwise replace with y

index = np.where(x==8) #returns index
print(index)

arr = np.where(x>8,x,0) #returns array
print(arr)

(array([1]),)
[ 10   0  16 100]


In [ ]:
print(mat)

[[10  3  5]
 [ 8  4  9]]


In [ ]:
index = np.where(mat>8)
print(index)

arr = np.where(mat>8,mat,0) #returns array
print(arr)

(array([0, 1]), array([0, 2]))
[[10  0  0]
 [ 0  0  9]]


In [ ]:

x = np.array([ 10,100 , 8 , 16 , 100 ])
max_val_idx = np.argmax(x)
print(max_val_idx)
min_val_idx = np.argmin(x)
print(min_val_idx)

1
2


###**Counting in nd array**

In [ ]:
a = np.random.randint(1,100,size=(100,))
print(a)

[27 60 23 42 34 53 44 54  4  2 17 95 33  4 13 74 15 85 99 27 78 84  3  2
 89 97 87 50 79 65 66 88 44 10 56 91 50 24 44 82 89 24 37 94 37 43 11 90
 24 28 27 31 16 36 55 45 51 69 42 46 71  4 87 80 38 14 87 21 83 69 82 13
 58 24 96 68 36 32  5  5 47  3 48 47 13 89 22 45 94 67 34 53 14 10 13 61
 76 99  7 92]


In [ ]:
val_reater_than_60 = np.count_nonzero(a==60)
print(val_reater_than_60)

1


In [ ]:
unique_value,count = np.unique(a,return_counts=True)
print(unique_value)
print(count)

[ 2  3  4  5  7 10 11 13 14 15 16 17 21 22 23 24 27 28 31 32 33 34 36 37
 38 42 43 44 45 46 47 48 50 51 53 54 55 56 58 60 61 65 66 67 68 69 71 74
 76 78 79 80 82 83 84 85 87 88 89 90 91 92 94 95 96 97 99]
[2 2 3 2 1 2 1 4 2 1 1 1 1 1 1 4 3 1 1 1 1 2 2 2 1 2 1 3 2 1 2 1 2 1 2 1 1
 1 1 1 1 1 1 1 1 2 1 1 1 1 1 1 2 1 1 1 3 1 3 1 1 1 2 1 1 1 2]


##**statistical function**

In [47]:
data = np.genfromtxt('student_scores.csv',delimiter=',',skip_header=1)
print(data)

[[78. 85. 82.]
 [56. 67. 72.]
 [89. 92. 88.]
 [45. 52. 58.]
 [70. 75. 80.]
 [92. 90. 91.]
 [61. 60. 62.]
 [55. 57. 54.]
 [88. 89. 87.]
 [74. 70. 76.]
 [66. 69. 68.]
 [80. 82. 81.]
 [59. 64. 60.]
 [73. 78. 74.]
 [91. 93. 90.]
 [68. 71. 69.]
 [77. 79. 78.]
 [84. 86. 85.]
 [62. 63. 65.]
 [95. 97. 96.]]


In [54]:
# statistics
math_marks = data[::,:1]
print(math_marks.T)

max_math_marks = np.max(math_marks)
print(max_math_marks)

min_math_marks = np.min(math_marks)
print(min_math_marks)

average_math_marks = np.mean(math_marks)
print(average_math_marks)

median_math_marks = np.median(math_marks)
print(median_math_marks)

#standard deviation
std_math_marks = np.std(math_marks)
print(std_math_marks)

[[78. 56. 89. 45. 70. 92. 61. 55. 88. 74. 66. 80. 59. 73. 91. 68. 77. 84.
  62. 95.]]
95.0
45.0
73.15
73.5
13.788672887555204


##**Linear algebra**

In [58]:
A = np.array([
    [1,2,3],
    [4,5,6]
])
B = np.array([
    [7,8],
    [9,10],
    [11,12
     ]
])
# a er column and b er row same length hote hobe
dot_product = np.dot(A,B)
print(dot_product)

#trace
print(np.trace(A))

[[ 58  64]
 [139 154]]
6


In [67]:
sq_mat = np.array([[1,2,3],
                   [4,5,6],
                   [7,8,9]])
det_of_sq = np.linalg.det(sq_mat)
print(det_of_sq)
rank_sq = np.linalg.matrix_rank(sq_mat)

print(det_of_sq)

print(rank_sq)


0.0
0.0
2
